### ISSUE TITLE
Input Number has problems with decimals since 6.2.6/6.2.7

### ISSUE THREAD

**Issue by kaipaysen** [sveltestrap/sveltestrap#70]
**Describe the bug**
Input of numbers with decimal places is broken since 6.2.6/6.2.7

**How to reproduce**

1. Goto https://sveltestrap.js.org/?path=/docs/form-input--docs#numbers 
2. Enter decimal numbers like "1,22".

**Expected behavior**
The value should stay "1,22"

**Screenshots**
https://github.com/sveltestrap/sveltestrap/assets/8957069/0274e922-722e-4415-a625-92e5eb8417d6

**Desktop (please complete the following information):**
Current Chrome on Mac OS

**Additional context**
I'm pretty sure it's related to https://github.com/sveltestrap/sveltestrap/pull/61

**Comment by ersimont** [comment]
I just ran into this. Is there any known workaround for now?

**Comment by kaipaysen** [comment]
Downgrade to 6.2.5 worked for me

**Comment by dysfunc** [comment]
Apologies for the delayed response. I've reviewed your issue and I'm hesitant to change this logic since it aligns with the [native `number` input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number) behavior. If you want to use decimals or commas, it seems like using a `text` input field with validation would make sense.

**Comment by kaipaysen** [comment]
Uhh, this is a breaking change. And I'm pretty sure Kommas in Numbers are absolute fine when your Locale tells the browser to use these.

**Comment by dysfunc** [comment]
I reread your issue and realized your example contains commas not decimals. There is an issue with decimals, but not with supporting commas. I plan to PR a fix for the decimals soon.
